<?php

class SetUp extends SocialAuthAppModel {

    public $useTable = false;
    protected $_requirementIssues = array();

    /**
     * Checks Requirements required for smooth operation
     * @return boolean
     */
    public function checkRequirements() {

        $this->checkBootstrapWriteable();
        $this->checkPHPVersion();
        $this->checkCurlEnabled();
        $this->checkLocalhost();
        if (empty($this->_requirementIssues)) {
            return false;
        }
        return true;
    }

    /**
     *
     */
    protected function checkPHPVersion() {
        if (version_compare(PHP_VERSION, '5.2', '<')) {

            $this->_requirementIssues[] = __('HybridAuth requires PHP 5.2 or higher');
        }
    }

    protected function checkCurlEnabled() {
        if (!in_array('curl', get_loaded_extensions())) {
            $this->_requirementIssues[] = __('HybridAuth will require to use <a href="http://php.net/manual/en/book.curl.php"  target="_blank">CURL library</a>. Please install/enable it before continuing.');
        }
    }

    protected function checkBootstrapWriteable() {
        $fileName = APP . 'Plugin' . DS . 'SocialAuth' . DS . 'Config' . DS . 'config.php';

        if (!is_writable($fileName)) {
            $this->_requirementIssues[] = __('HybridAuth Configuration file must be writable for installation to work');
        }
    }

    protected function checkLocalhost() {

        if ($_SERVER["SERVER_NAME"] == "localhost" || $_SERVER["SERVER_NAME"] == "127.0.0.1") {
            $this->_requirementIssues[] = __('HybridAuth will not work properly in localhost, as some social networks DO NOT TRUST localhost requests');
        }
    }

    /**
     * Requirement Errors, if they exist
     * @return array
     */
    public function getRequirementIssues() {
        return $this->_requirementIssues;
    }

    public function getHybridVersion() {
        return Hybrid_Auth::$version;
    }

    public function effectAuth(){
        return Hybrid_Endpoint::process();
    }

    public function saveSettings($formData) {
        $configTemplate = file_get_contents(HYBRID_AUTH_LIB_PATH . "/resources/config.php.tpl");

        foreach ($formData as $key => $value) {
            $value = strip_tags($value);
            $amendedKey = "#$key#";

            $configTemplate = str_replace($amendedKey, $value, $configTemplate);
        }

        $configTemplate = str_replace("<?php", "<?php\n\t#AUTOGENERATED BY HYBRIDAUTH " . $this->getHybridVersion() . " INSTALLER - " . date("l jS \of F Y h:i:s A") . "\n", $configTemplate);

        $isInstalled = file_put_contents(APP . 'Plugin' . DS . 'SocialAuth' . DS . 'Config' . DS . 'config.php', $configTemplate);

        if (!$isInstalled) {
            return false;
        }
        return true;
    }

}

?>
